version: 2.1

# Some reusable YAML definitions
# TODO may need 2.12 cache and 2.13 cache
save_cache: &save_cache
  - save_cache:
      key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-2
      paths:
        - "~/.ivy2/cache"
        - "~/.sbt"
        - "~/.m2"
        - "~/.cache"
        - "target"

load_cache: &load_cache
  - restore_cache:
      key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-2

scala_212: &scala_212
  SCALA_VERSION: 2.12.12

scala_213: &scala_213
  SCALA_VERSION: 2.13.3

jdk_8: &jdk_8
  JDK_VERSION: 8

jdk_11: &jdk_11
  JDK_VERSION: 11

filter_tags: &filter_tags
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

java_opts: &java_opts
  JAVA_OPTS: -Xmx2g -Xms1g -Dfile.encoding=UTF8 -Xss16M -XX:+UseParallelGC -XX:ReservedCodeCacheSize=512M

save_test_results: &save_test_results
  - run:
      command: |
        mkdir -p test-reports
        find . -type f -regex ".*/target/test-reports/.*xml" -exec cp {} test-reports/ \;
      name: Save test results

localstack: &localstack
  - image: localstack/localstack
    environment:
      LOCALSTACK_HOST: localstack
      SERVICES: 's3,dynamodb'
      USE_SSL: "false"
      DEFAULT_REGION: 'us-east-1'
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: dummy-key
      AWS_SECRET_ACCESS_KEY: dummy-key
      DEBUG: "1"

# CircleCI jobs

jobs:
  tests_core_213:
    docker:
      - image: hseeberger/scala-sbt:11.0.8_1.4.1_2.13.3
    environment:
      - <<: *java_opts
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - <<: *load_cache
      - run: sbt -J-Xmx3g -J-Xms3g ++$SCALA_VERSION zio-aws-core/test zio-aws-akka-http/test zio-aws-http4s/test zio-aws-netty/test
      - <<: *save_cache
      - <<: *save_test_results
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: .
          paths:
            - project
            - target
            - zio-aws-*
            - generated

  integration_tests_213:
    docker:
      - image: hseeberger/scala-sbt:11.0.8_1.4.1_2.13.3
      - <<: *localstack
    environment:
      - <<: *scala_213
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - <<: *load_cache
      - run: sbt -J-Xmx2500m -J-Xms2500m ++$SCALA_VERSION examples/compile integtests/test
      - <<: *save_cache
      - <<: *save_test_results
      - store_test_results:
          path: test-reports

  compile_sdk_projects:
    parameters:
      commands:
        description: SBT commands to run
        type: string
      scala_version:
        description: Scala version
        type: string
    docker:
      - image: hseeberger/scala-sbt:11.0.8_1.4.1_2.13.3
    environment:
      - SCALA_VERSION: << parameters.scala_version >>
      - <<: *java_opts
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - <<: *load_cache
      - run: sbt ++$SCALA_VERSION << parameters.commands >>
  #      - <<: *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - target/sonatype-staging

  publish_local:
    parameters:
      scala_version:
        description: Scala version
        type: string
    docker:
      - image: hseeberger/scala-sbt:11.0.8_1.4.1_2.13.3
    environment:
      - SCALA_VERSION: << parameters.scala_version >>
      - <<: *java_opts
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - <<: *load_cache
      - run: sbt ++$SCALA_VERSION -J-Xmx2500m -J-Xms2500m publishLocal

  tests_core_212:
    docker:
      - image: hseeberger/scala-sbt:11.0.8_1.4.1_2.13.3
    environment:
      - <<: *scala_212
    steps:
      - checkout
      - <<: *load_cache
      - run: sbt -J-Xmx3g -J-Xms3g ++$SCALA_VERSION zio-aws-core/test zio-aws-akka-http/test zio-aws-http4s/test zio-aws-netty/test
      - <<: *save_cache
      - <<: *save_test_results
      - store_test_results:
          path: test-reports

#  integration_tests_212:
#    docker:
#      - image: hseeberger/scala-sbt:8u265_1.3.13_2.13.3
#      - <<: *localstack
#    environment:
#      - <<: *scala_212
#    steps:
#      - checkout
#      - <<: *load_cache
#      - run: sbt -J-Xmx2500m -J-Xms2500m ++$SCALA_VERSION examples/compile integtests/test
#      - <<: *save_cache
#      - <<: *save_test_results
#      - store_test_results:
#          path: test-reports

workflows:
  version: 2
  build:
    jobs:
#      - tests_core_212:
#          filters:
#            <<: *filter_tags
#      - integration_tests_212:
#          requires:
#            - tests_core_212
#          filters:
#            <<: *filter_tags
      - tests_core_213:
          filters:
            <<: *filter_tags
      - integration_tests_213:
          requires:
            - tests_core_213
          filters:
            <<: *filter_tags
      - compile_sdk_projects:
          requires:
            - tests_core_213
#            - tests_core_212
          filters:
            <<: *filter_tags
          matrix:
            parameters:
              scala_version:
                - 2.13.3
                # - 2.12.12
                # NOTE this part is automatically generated
              commands: ["zio-aws-accessanalyzer/compile zio-aws-accessanalyzer/publish zio-aws-acm/compile zio-aws-acm/publish zio-aws-acmpca/compile zio-aws-acmpca/publish zio-aws-alexaforbusiness/compile zio-aws-alexaforbusiness/publish zio-aws-amplify/compile zio-aws-amplify/publish zio-aws-apigateway/compile zio-aws-apigateway/publish zio-aws-apigatewaymanagementapi/compile zio-aws-apigatewaymanagementapi/publish zio-aws-apigatewayv2/compile zio-aws-apigatewayv2/publish zio-aws-appconfig/compile zio-aws-appconfig/publish zio-aws-appflow/compile zio-aws-appflow/publish zio-aws-applicationautoscaling/compile zio-aws-applicationautoscaling/publish zio-aws-applicationdiscovery/compile zio-aws-applicationdiscovery/publish zio-aws-applicationinsights/compile zio-aws-applicationinsights/publish zio-aws-appmesh/compile zio-aws-appmesh/publish zio-aws-appstream/compile zio-aws-appstream/publish zio-aws-appsync/compile zio-aws-appsync/publish zio-aws-athena/compile zio-aws-athena/publish zio-aws-autoscaling/compile zio-aws-autoscaling/publish zio-aws-autoscalingplans/compile zio-aws-autoscalingplans/publish zio-aws-backup/compile zio-aws-backup/publish zio-aws-batch/compile zio-aws-batch/publish zio-aws-braket/compile zio-aws-braket/publish zio-aws-budgets/compile zio-aws-budgets/publish zio-aws-chime/compile zio-aws-chime/publish zio-aws-cloud9/compile zio-aws-cloud9/publish zio-aws-clouddirectory/compile zio-aws-clouddirectory/publish zio-aws-cloudformation/compile zio-aws-cloudformation/publish zio-aws-cloudfront/compile zio-aws-cloudfront/publish zio-aws-cloudhsm/compile zio-aws-cloudhsm/publish","zio-aws-cloudhsmv2/compile zio-aws-cloudhsmv2/publish zio-aws-cloudsearch/compile zio-aws-cloudsearch/publish zio-aws-cloudsearchdomain/compile zio-aws-cloudsearchdomain/publish zio-aws-cloudtrail/compile zio-aws-cloudtrail/publish zio-aws-cloudwatch/compile zio-aws-cloudwatch/publish zio-aws-cloudwatchevents/compile zio-aws-cloudwatchevents/publish zio-aws-cloudwatchlogs/compile zio-aws-cloudwatchlogs/publish zio-aws-codeartifact/compile zio-aws-codeartifact/publish zio-aws-codebuild/compile zio-aws-codebuild/publish zio-aws-codecommit/compile zio-aws-codecommit/publish zio-aws-codedeploy/compile zio-aws-codedeploy/publish zio-aws-codeguruprofiler/compile zio-aws-codeguruprofiler/publish zio-aws-codegurureviewer/compile zio-aws-codegurureviewer/publish zio-aws-codepipeline/compile zio-aws-codepipeline/publish zio-aws-codestar/compile zio-aws-codestar/publish zio-aws-codestarconnections/compile zio-aws-codestarconnections/publish zio-aws-codestarnotifications/compile zio-aws-codestarnotifications/publish zio-aws-cognitoidentity/compile zio-aws-cognitoidentity/publish zio-aws-cognitoidentityprovider/compile zio-aws-cognitoidentityprovider/publish zio-aws-cognitosync/compile zio-aws-cognitosync/publish zio-aws-comprehend/compile zio-aws-comprehend/publish zio-aws-comprehendmedical/compile zio-aws-comprehendmedical/publish zio-aws-computeoptimizer/compile zio-aws-computeoptimizer/publish zio-aws-config/compile zio-aws-config/publish zio-aws-connect/compile zio-aws-connect/publish zio-aws-connectparticipant/compile zio-aws-connectparticipant/publish zio-aws-costandusagereport/compile zio-aws-costandusagereport/publish zio-aws-costexplorer/compile zio-aws-costexplorer/publish zio-aws-databasemigration/compile zio-aws-databasemigration/publish"]
      - publish_local:
          requires:
            - compile_sdk_projects
          matrix:
            parameters:
              scala_version:
                - 2.13.3
                - 2.12.12
